# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
    silent: true

  build:
    desc: Build go app
    cmds:
      - go build -o once main.go
